// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDevelopment {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsIdVPuXUBWo3wxeHtrwpaJNIXHCdIWVw',
    appId: '1:111279810147:web:ccfeea3e31e3b1282efa56',
    messagingSenderId: '111279810147',
    projectId: 'flutter-flavors-demo-e8dca',
    authDomain: 'flutter-flavors-demo-e8dca.firebaseapp.com',
    storageBucket: 'flutter-flavors-demo-e8dca.firebasestorage.app',
    measurementId: 'G-30KR3RBXCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmQz40-hc6enmF5dxM0rWtJj-anHwOhj4',
    appId: '1:111279810147:android:4c8b46967bf754422efa56',
    messagingSenderId: '111279810147',
    projectId: 'flutter-flavors-demo-e8dca',
    storageBucket: 'flutter-flavors-demo-e8dca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0W6k-hzuqKu_b36vt0qrd_W7YEwYZmc',
    appId: '1:111279810147:ios:886f258210b7577f2efa56',
    messagingSenderId: '111279810147',
    projectId: 'flutter-flavors-demo-e8dca',
    storageBucket: 'flutter-flavors-demo-e8dca.firebasestorage.app',
    iosBundleId: 'com.example.development',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj0W6k-hzuqKu_b36vt0qrd_W7YEwYZmc',
    appId: '1:111279810147:ios:b5dab1273932b8692efa56',
    messagingSenderId: '111279810147',
    projectId: 'flutter-flavors-demo-e8dca',
    storageBucket: 'flutter-flavors-demo-e8dca.firebasestorage.app',
    iosBundleId: 'com.example.flavors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsIdVPuXUBWo3wxeHtrwpaJNIXHCdIWVw',
    appId: '1:111279810147:web:90885da02d6448a92efa56',
    messagingSenderId: '111279810147',
    projectId: 'flutter-flavors-demo-e8dca',
    authDomain: 'flutter-flavors-demo-e8dca.firebaseapp.com',
    storageBucket: 'flutter-flavors-demo-e8dca.firebasestorage.app',
    measurementId: 'G-GJH5C0D5ZV',
  );
}